[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_token_transfer = "FgzRLHDfd36md7g5jm8igzAkyfVdC7MXTEJpU7xTLW3K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/johnes/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
